/*
 * CDMS Customer API
 * CDMS Customer API will provide a set of the REST API for operations on Customer Data Management System (CDMS)
 *
 * OpenAPI spec version: 1.0
 * Contact: johnson_ouyang@toyota.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.RequestHeader;
import ca.toyota.bizservice.api.cdms.VehicleOwnership;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Request for the vehicle ownership bulk APIs
 */
@ApiModel(description = "Request for the vehicle ownership bulk APIs")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:36.821-05:00")
public class BulkOwnershipRequest {
  @JsonProperty("requestHeader")
  private RequestHeader requestHeader = null;

  @JsonProperty("vehicleOwnerships")
  private List<VehicleOwnership> vehicleOwnerships = new ArrayList<>();

  public BulkOwnershipRequest requestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
    return this;
  }

   /**
   * Get requestHeader
   * @return requestHeader
  **/
  @ApiModelProperty(required = true, value = "")
  public RequestHeader getRequestHeader() {
    return requestHeader;
  }

  public void setRequestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
  }

  public BulkOwnershipRequest vehicleOwnerships(List<VehicleOwnership> vehicleOwnerships) {
    this.vehicleOwnerships = vehicleOwnerships;
    return this;
  }

  public BulkOwnershipRequest addVehicleOwnershipsItem(VehicleOwnership vehicleOwnershipsItem) {
    this.vehicleOwnerships.add(vehicleOwnershipsItem);
    return this;
  }

   /**
   * Ownerships for the vehciles
   * @return vehicleOwnerships
  **/
  @ApiModelProperty(required = true, value = "Ownerships for the vehciles")
  public List<VehicleOwnership> getVehicleOwnerships() {
    return vehicleOwnerships;
  }

  public void setVehicleOwnerships(List<VehicleOwnership> vehicleOwnerships) {
    this.vehicleOwnerships = vehicleOwnerships;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkOwnershipRequest bulkOwnershipRequest = (BulkOwnershipRequest) o;
    return Objects.equals(this.requestHeader, bulkOwnershipRequest.requestHeader) &&
        Objects.equals(this.vehicleOwnerships, bulkOwnershipRequest.vehicleOwnerships);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestHeader, vehicleOwnerships);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkOwnershipRequest {\n");
    
    sb.append("    requestHeader: ").append(toIndentedString(requestHeader)).append("\n");
    sb.append("    vehicleOwnerships: ").append(toIndentedString(vehicleOwnerships)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

