/*
 * Customer Update Integration API
 * OICC API will process OICC request and broadcast to downstream applications via broadcast API.  Briefly, OICC will call customer API to match/create/update customer profile for all involve parties,  then call SAP if required, after SAP process success broad cast CustomerProfileChangeEvent or  OwnershipChangeEvent accordingly.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * CASLStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:37.695-05:00")
public class CASLStatus {
  /**
   * CASL (Canadian Anti-Spam Law) status
   */
  public enum StatusEnum {
    YES_ECONTACT("YES_ECONTACT"),
    
    NO_ECONTACT("NO_ECONTACT");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  /**
   * Source code for CASL status.
   */
  public enum SourceCodeEnum {
    CRM("CRM"),
    
    DEALERCIC("DEALERCIC"),
    
    JAM("JAM"),
    
    LEXUS_CA("LEXUS.CA"),
    
    ODS("ODS"),
    
    OTHERCIC("OTHERCIC"),
    
    RDR("RDR"),
    
    SERVICE_REPAIR_ORDER("SERVICE REPAIR ORDER"),
    
    TCICIC("TCICIC"),
    
    TOYOTA_CA("TOYOTA.CA"),
    
    USED_VEHICLE("USED VEHICLE");

    private String value;

    SourceCodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceCodeEnum fromValue(String text) {
      for (SourceCodeEnum b : SourceCodeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("sourceCode")
  private SourceCodeEnum sourceCode = null;

  @JsonProperty("effectiveDateTime")
  private OffsetDateTime effectiveDateTime = null;

  public CASLStatus status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * CASL (Canadian Anti-Spam Law) status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "CASL (Canadian Anti-Spam Law) status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public CASLStatus sourceCode(SourceCodeEnum sourceCode) {
    this.sourceCode = sourceCode;
    return this;
  }

   /**
   * Source code for CASL status.
   * @return sourceCode
  **/
  @ApiModelProperty(example = "toyota.ca", required = true, value = "Source code for CASL status.")
  public SourceCodeEnum getSourceCode() {
    return sourceCode;
  }

  public void setSourceCode(SourceCodeEnum sourceCode) {
    this.sourceCode = sourceCode;
  }

  public CASLStatus effectiveDateTime(OffsetDateTime effectiveDateTime) {
    this.effectiveDateTime = effectiveDateTime;
    return this;
  }

   /**
   * Effective timestamp for CASL status
   * @return effectiveDateTime
  **/
  @ApiModelProperty(example = "2017-09-07T10:40:52.000+0000", required = true, value = "Effective timestamp for CASL status")
  public OffsetDateTime getEffectiveDateTime() {
    return effectiveDateTime;
  }

  public void setEffectiveDateTime(OffsetDateTime effectiveDateTime) {
    this.effectiveDateTime = effectiveDateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CASLStatus caSLStatus = (CASLStatus) o;
    return Objects.equals(this.status, caSLStatus.status) &&
        Objects.equals(this.sourceCode, caSLStatus.sourceCode) &&
        Objects.equals(this.effectiveDateTime, caSLStatus.effectiveDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, sourceCode, effectiveDateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CASLStatus {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    sourceCode: ").append(toIndentedString(sourceCode)).append("\n");
    sb.append("    effectiveDateTime: ").append(toIndentedString(effectiveDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

