/*
 * Customer Update Integration API
 * OICC API will process OICC request and broadcast to downstream applications via broadcast API.  Briefly, OICC will call customer API to match/create/update customer profile for all involve parties,  then call SAP if required, after SAP process success broad cast CustomerProfileChangeEvent or  OwnershipChangeEvent accordingly.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;

/**
 * Incentive
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:37.695-05:00")
public class Incentive {
  @JsonProperty("cnifCompletedIndicator")
  private Boolean cnifCompletedIndicator = null;

  @JsonProperty("tmmcLoi")
  private String tmmcLoi = null;

  @JsonProperty("fleetAccountNumber")
  private String fleetAccountNumber = null;

  @JsonProperty("promotionRate")
  private String promotionRate = null;

  @JsonProperty("tmmcPurchaseIndicator")
  private Boolean tmmcPurchaseIndicator = null;

  @JsonProperty("billOfSaleDate")
  private LocalDate billOfSaleDate = null;

  public Incentive cnifCompletedIndicator(Boolean cnifCompletedIndicator) {
    this.cnifCompletedIndicator = cnifCompletedIndicator;
    return this;
  }

   /**
   * Get cnifCompletedIndicator
   * @return cnifCompletedIndicator
  **/
  @ApiModelProperty(value = "")
  public Boolean isCnifCompletedIndicator() {
    return cnifCompletedIndicator;
  }

  public void setCnifCompletedIndicator(Boolean cnifCompletedIndicator) {
    this.cnifCompletedIndicator = cnifCompletedIndicator;
  }

  public Incentive tmmcLoi(String tmmcLoi) {
    this.tmmcLoi = tmmcLoi;
    return this;
  }

   /**
   * Get tmmcLoi
   * @return tmmcLoi
  **/
  @ApiModelProperty(value = "")
  public String getTmmcLoi() {
    return tmmcLoi;
  }

  public void setTmmcLoi(String tmmcLoi) {
    this.tmmcLoi = tmmcLoi;
  }

  public Incentive fleetAccountNumber(String fleetAccountNumber) {
    this.fleetAccountNumber = fleetAccountNumber;
    return this;
  }

   /**
   * Get fleetAccountNumber
   * @return fleetAccountNumber
  **/
  @ApiModelProperty(value = "")
  public String getFleetAccountNumber() {
    return fleetAccountNumber;
  }

  public void setFleetAccountNumber(String fleetAccountNumber) {
    this.fleetAccountNumber = fleetAccountNumber;
  }

  public Incentive promotionRate(String promotionRate) {
    this.promotionRate = promotionRate;
    return this;
  }

   /**
   * Get promotionRate
   * @return promotionRate
  **/
  @ApiModelProperty(value = "")
  public String getPromotionRate() {
    return promotionRate;
  }

  public void setPromotionRate(String promotionRate) {
    this.promotionRate = promotionRate;
  }

  public Incentive tmmcPurchaseIndicator(Boolean tmmcPurchaseIndicator) {
    this.tmmcPurchaseIndicator = tmmcPurchaseIndicator;
    return this;
  }

   /**
   * Get tmmcPurchaseIndicator
   * @return tmmcPurchaseIndicator
  **/
  @ApiModelProperty(value = "")
  public Boolean isTmmcPurchaseIndicator() {
    return tmmcPurchaseIndicator;
  }

  public void setTmmcPurchaseIndicator(Boolean tmmcPurchaseIndicator) {
    this.tmmcPurchaseIndicator = tmmcPurchaseIndicator;
  }

  public Incentive billOfSaleDate(LocalDate billOfSaleDate) {
    this.billOfSaleDate = billOfSaleDate;
    return this;
  }

   /**
   * Get billOfSaleDate
   * @return billOfSaleDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getBillOfSaleDate() {
    return billOfSaleDate;
  }

  public void setBillOfSaleDate(LocalDate billOfSaleDate) {
    this.billOfSaleDate = billOfSaleDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Incentive incentive = (Incentive) o;
    return Objects.equals(this.cnifCompletedIndicator, incentive.cnifCompletedIndicator) &&
        Objects.equals(this.tmmcLoi, incentive.tmmcLoi) &&
        Objects.equals(this.fleetAccountNumber, incentive.fleetAccountNumber) &&
        Objects.equals(this.promotionRate, incentive.promotionRate) &&
        Objects.equals(this.tmmcPurchaseIndicator, incentive.tmmcPurchaseIndicator) &&
        Objects.equals(this.billOfSaleDate, incentive.billOfSaleDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cnifCompletedIndicator, tmmcLoi, fleetAccountNumber, promotionRate, tmmcPurchaseIndicator, billOfSaleDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Incentive {\n");
    
    sb.append("    cnifCompletedIndicator: ").append(toIndentedString(cnifCompletedIndicator)).append("\n");
    sb.append("    tmmcLoi: ").append(toIndentedString(tmmcLoi)).append("\n");
    sb.append("    fleetAccountNumber: ").append(toIndentedString(fleetAccountNumber)).append("\n");
    sb.append("    promotionRate: ").append(toIndentedString(promotionRate)).append("\n");
    sb.append("    tmmcPurchaseIndicator: ").append(toIndentedString(tmmcPurchaseIndicator)).append("\n");
    sb.append("    billOfSaleDate: ").append(toIndentedString(billOfSaleDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

