/*
 * CDMS Customer API
 * CDMS Customer API will provide a set of the REST API for operations on Customer Data Management System (CDMS)
 *
 * OpenAPI spec version: 1.0
 * Contact: johnson_ouyang@toyota.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.ResponseHeader;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MatchCustomerResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:36.821-05:00")
public class MatchCustomerResponse {
  @JsonProperty("responseHeader")
  private ResponseHeader responseHeader = null;

  @JsonProperty("isMatch")
  private Boolean isMatch = null;

  @JsonProperty("consumerIDs")
  private List<String> consumerIDs = null;

  public MatchCustomerResponse responseHeader(ResponseHeader responseHeader) {
    this.responseHeader = responseHeader;
    return this;
  }

   /**
   * Get responseHeader
   * @return responseHeader
  **/
  @ApiModelProperty(value = "")
  public ResponseHeader getResponseHeader() {
    return responseHeader;
  }

  public void setResponseHeader(ResponseHeader responseHeader) {
    this.responseHeader = responseHeader;
  }

  public MatchCustomerResponse isMatch(Boolean isMatch) {
    this.isMatch = isMatch;
    return this;
  }

   /**
   * true if the customer is matched, otherwise false.
   * @return isMatch
  **/
  @ApiModelProperty(value = "true if the customer is matched, otherwise false.")
  public Boolean isIsMatch() {
    return isMatch;
  }

  public void setIsMatch(Boolean isMatch) {
    this.isMatch = isMatch;
  }

  public MatchCustomerResponse consumerIDs(List<String> consumerIDs) {
    this.consumerIDs = consumerIDs;
    return this;
  }

  public MatchCustomerResponse addConsumerIDsItem(String consumerIDsItem) {
    if (this.consumerIDs == null) {
      this.consumerIDs = new ArrayList<>();
    }
    this.consumerIDs.add(consumerIDsItem);
    return this;
  }

   /**
   * Array of customer IDs matched the specified customer
   * @return consumerIDs
  **/
  @ApiModelProperty(value = "Array of customer IDs matched the specified customer")
  public List<String> getConsumerIDs() {
    return consumerIDs;
  }

  public void setConsumerIDs(List<String> consumerIDs) {
    this.consumerIDs = consumerIDs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchCustomerResponse matchCustomerResponse = (MatchCustomerResponse) o;
    return Objects.equals(this.responseHeader, matchCustomerResponse.responseHeader) &&
        Objects.equals(this.isMatch, matchCustomerResponse.isMatch) &&
        Objects.equals(this.consumerIDs, matchCustomerResponse.consumerIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseHeader, isMatch, consumerIDs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchCustomerResponse {\n");
    
    sb.append("    responseHeader: ").append(toIndentedString(responseHeader)).append("\n");
    sb.append("    isMatch: ").append(toIndentedString(isMatch)).append("\n");
    sb.append("    consumerIDs: ").append(toIndentedString(consumerIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

