/*
 * CDMS Customer API
 * CDMS Customer API will provide a set of the REST API for operations on Customer Data Management System (CDMS)
 *
 * OpenAPI spec version: 1.0
 * Contact: johnson_ouyang@toyota.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.Customer;
import ca.toyota.bizservice.api.cdms.ResponseHeader;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MergeCustomerResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:36.821-05:00")
public class MergeCustomerResponse {
  @JsonProperty("responseHeader")
  private ResponseHeader responseHeader = null;

  @JsonProperty("customer")
  private Customer customer = null;

  @JsonProperty("mergedCustomerIDs")
  private List<String> mergedCustomerIDs = null;

  @JsonProperty("isContinueMerge")
  private Boolean isContinueMerge = null;

  public MergeCustomerResponse responseHeader(ResponseHeader responseHeader) {
    this.responseHeader = responseHeader;
    return this;
  }

   /**
   * Get responseHeader
   * @return responseHeader
  **/
  @ApiModelProperty(value = "")
  public ResponseHeader getResponseHeader() {
    return responseHeader;
  }

  public void setResponseHeader(ResponseHeader responseHeader) {
    this.responseHeader = responseHeader;
  }

  public MergeCustomerResponse customer(Customer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @ApiModelProperty(value = "")
  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.customer = customer;
  }

  public MergeCustomerResponse mergedCustomerIDs(List<String> mergedCustomerIDs) {
    this.mergedCustomerIDs = mergedCustomerIDs;
    return this;
  }

  public MergeCustomerResponse addMergedCustomerIDsItem(String mergedCustomerIDsItem) {
    if (this.mergedCustomerIDs == null) {
      this.mergedCustomerIDs = new ArrayList<>();
    }
    this.mergedCustomerIDs.add(mergedCustomerIDsItem);
    return this;
  }

   /**
   * Array of customer IDs being merged from
   * @return mergedCustomerIDs
  **/
  @ApiModelProperty(value = "Array of customer IDs being merged from")
  public List<String> getMergedCustomerIDs() {
    return mergedCustomerIDs;
  }

  public void setMergedCustomerIDs(List<String> mergedCustomerIDs) {
    this.mergedCustomerIDs = mergedCustomerIDs;
  }

  public MergeCustomerResponse isContinueMerge(Boolean isContinueMerge) {
    this.isContinueMerge = isContinueMerge;
    return this;
  }

   /**
   * true if the merge process has been executed, and need merge again, otherwise false
   * @return isContinueMerge
  **/
  @ApiModelProperty(value = "true if the merge process has been executed, and need merge again, otherwise false")
  public Boolean isIsContinueMerge() {
    return isContinueMerge;
  }

  public void setIsContinueMerge(Boolean isContinueMerge) {
    this.isContinueMerge = isContinueMerge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergeCustomerResponse mergeCustomerResponse = (MergeCustomerResponse) o;
    return Objects.equals(this.responseHeader, mergeCustomerResponse.responseHeader) &&
        Objects.equals(this.customer, mergeCustomerResponse.customer) &&
        Objects.equals(this.mergedCustomerIDs, mergeCustomerResponse.mergedCustomerIDs) &&
        Objects.equals(this.isContinueMerge, mergeCustomerResponse.isContinueMerge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseHeader, customer, mergedCustomerIDs, isContinueMerge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergeCustomerResponse {\n");
    
    sb.append("    responseHeader: ").append(toIndentedString(responseHeader)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    mergedCustomerIDs: ").append(toIndentedString(mergedCustomerIDs)).append("\n");
    sb.append("    isContinueMerge: ").append(toIndentedString(isContinueMerge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

