/*
 * CDMS Customer API
 * CDMS Customer API will provide a set of the REST API for operations on Customer Data Management System (CDMS)
 *
 * OpenAPI spec version: 1.0
 * Contact: johnson_ouyang@toyota.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.RequestHeader;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MergeCustomerRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:36.821-05:00")
public class MergeCustomerRequest {
  @JsonProperty("requestHeader")
  private RequestHeader requestHeader = null;

  @JsonProperty("customerID")
  private Long customerID = null;

  @JsonProperty("mergeCandidateCustomerIDs")
  private List<String> mergeCandidateCustomerIDs = null;

  public MergeCustomerRequest requestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
    return this;
  }

   /**
   * Get requestHeader
   * @return requestHeader
  **/
  @ApiModelProperty(required = true, value = "")
  public RequestHeader getRequestHeader() {
    return requestHeader;
  }

  public void setRequestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
  }

  public MergeCustomerRequest customerID(Long customerID) {
    this.customerID = customerID;
    return this;
  }

   /**
   * Customer to be merged to (StandardParty)
   * @return customerID
  **/
  @ApiModelProperty(required = true, value = "Customer to be merged to (StandardParty)")
  public Long getCustomerID() {
    return customerID;
  }

  public void setCustomerID(Long customerID) {
    this.customerID = customerID;
  }

  public MergeCustomerRequest mergeCandidateCustomerIDs(List<String> mergeCandidateCustomerIDs) {
    this.mergeCandidateCustomerIDs = mergeCandidateCustomerIDs;
    return this;
  }

  public MergeCustomerRequest addMergeCandidateCustomerIDsItem(String mergeCandidateCustomerIDsItem) {
    if (this.mergeCandidateCustomerIDs == null) {
      this.mergeCandidateCustomerIDs = new ArrayList<>();
    }
    this.mergeCandidateCustomerIDs.add(mergeCandidateCustomerIDsItem);
    return this;
  }

   /**
   * Array of customer IDs to be merged from
   * @return mergeCandidateCustomerIDs
  **/
  @ApiModelProperty(value = "Array of customer IDs to be merged from")
  public List<String> getMergeCandidateCustomerIDs() {
    return mergeCandidateCustomerIDs;
  }

  public void setMergeCandidateCustomerIDs(List<String> mergeCandidateCustomerIDs) {
    this.mergeCandidateCustomerIDs = mergeCandidateCustomerIDs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergeCustomerRequest mergeCustomerRequest = (MergeCustomerRequest) o;
    return Objects.equals(this.requestHeader, mergeCustomerRequest.requestHeader) &&
        Objects.equals(this.customerID, mergeCustomerRequest.customerID) &&
        Objects.equals(this.mergeCandidateCustomerIDs, mergeCustomerRequest.mergeCandidateCustomerIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestHeader, customerID, mergeCandidateCustomerIDs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergeCustomerRequest {\n");
    
    sb.append("    requestHeader: ").append(toIndentedString(requestHeader)).append("\n");
    sb.append("    customerID: ").append(toIndentedString(customerID)).append("\n");
    sb.append("    mergeCandidateCustomerIDs: ").append(toIndentedString(mergeCandidateCustomerIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

