/*
 * Customer Update Integration API
 * OICC API will process OICC request and broadcast to downstream applications via broadcast API.  Briefly, OICC will call customer API to match/create/update customer profile for all involve parties,  then call SAP if required, after SAP process success broad cast CustomerProfileChangeEvent or  OwnershipChangeEvent accordingly.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * OiccExtraInfoSales
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:37.695-05:00")
public class OiccExtraInfoSales {
  @JsonProperty("salesPersonToyotaID")
  private String salesPersonToyotaID = null;

  @JsonProperty("businessManagerToyotaID")
  private String businessManagerToyotaID = null;

  public OiccExtraInfoSales salesPersonToyotaID(String salesPersonToyotaID) {
    this.salesPersonToyotaID = salesPersonToyotaID;
    return this;
  }

   /**
   * Get salesPersonToyotaID
   * @return salesPersonToyotaID
  **/
  @ApiModelProperty(value = "")
  public String getSalesPersonToyotaID() {
    return salesPersonToyotaID;
  }

  public void setSalesPersonToyotaID(String salesPersonToyotaID) {
    this.salesPersonToyotaID = salesPersonToyotaID;
  }

  public OiccExtraInfoSales businessManagerToyotaID(String businessManagerToyotaID) {
    this.businessManagerToyotaID = businessManagerToyotaID;
    return this;
  }

   /**
   * Get businessManagerToyotaID
   * @return businessManagerToyotaID
  **/
  @ApiModelProperty(value = "")
  public String getBusinessManagerToyotaID() {
    return businessManagerToyotaID;
  }

  public void setBusinessManagerToyotaID(String businessManagerToyotaID) {
    this.businessManagerToyotaID = businessManagerToyotaID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OiccExtraInfoSales oiccExtraInfoSales = (OiccExtraInfoSales) o;
    return Objects.equals(this.salesPersonToyotaID, oiccExtraInfoSales.salesPersonToyotaID) &&
        Objects.equals(this.businessManagerToyotaID, oiccExtraInfoSales.businessManagerToyotaID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salesPersonToyotaID, businessManagerToyotaID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OiccExtraInfoSales {\n");
    
    sb.append("    salesPersonToyotaID: ").append(toIndentedString(salesPersonToyotaID)).append("\n");
    sb.append("    businessManagerToyotaID: ").append(toIndentedString(businessManagerToyotaID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

