/*
 * Customer Update Integration API
 * OICC API will process OICC request and broadcast to downstream applications via broadcast API.  Briefly, OICC will call customer API to match/create/update customer profile for all involve parties,  then call SAP if required, after SAP process success broad cast CustomerProfileChangeEvent or  OwnershipChangeEvent accordingly.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * OiccExtraInfoDeal
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:37.695-05:00")
public class OiccExtraInfoDeal {
  @JsonProperty("dealNumber")
  private String dealNumber = null;

  @JsonProperty("dealType")
  private String dealType = null;

  @JsonProperty("dealSubType")
  private String dealSubType = null;

  @JsonProperty("sapDealType")
  private String sapDealType = null;

  public OiccExtraInfoDeal dealNumber(String dealNumber) {
    this.dealNumber = dealNumber;
    return this;
  }

   /**
   * Get dealNumber
   * @return dealNumber
  **/
  @ApiModelProperty(value = "")
  public String getDealNumber() {
    return dealNumber;
  }

  public void setDealNumber(String dealNumber) {
    this.dealNumber = dealNumber;
  }

  public OiccExtraInfoDeal dealType(String dealType) {
    this.dealType = dealType;
    return this;
  }

   /**
   * Get dealType
   * @return dealType
  **/
  @ApiModelProperty(value = "")
  public String getDealType() {
    return dealType;
  }

  public void setDealType(String dealType) {
    this.dealType = dealType;
  }

  public OiccExtraInfoDeal dealSubType(String dealSubType) {
    this.dealSubType = dealSubType;
    return this;
  }

   /**
   * Get dealSubType
   * @return dealSubType
  **/
  @ApiModelProperty(value = "")
  public String getDealSubType() {
    return dealSubType;
  }

  public void setDealSubType(String dealSubType) {
    this.dealSubType = dealSubType;
  }

  public OiccExtraInfoDeal sapDealType(String sapDealType) {
    this.sapDealType = sapDealType;
    return this;
  }

   /**
   * Get sapDealType
   * @return sapDealType
  **/
  @ApiModelProperty(value = "")
  public String getSapDealType() {
    return sapDealType;
  }

  public void setSapDealType(String sapDealType) {
    this.sapDealType = sapDealType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OiccExtraInfoDeal oiccExtraInfoDeal = (OiccExtraInfoDeal) o;
    return Objects.equals(this.dealNumber, oiccExtraInfoDeal.dealNumber) &&
        Objects.equals(this.dealType, oiccExtraInfoDeal.dealType) &&
        Objects.equals(this.dealSubType, oiccExtraInfoDeal.dealSubType) &&
        Objects.equals(this.sapDealType, oiccExtraInfoDeal.sapDealType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dealNumber, dealType, dealSubType, sapDealType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OiccExtraInfoDeal {\n");
    
    sb.append("    dealNumber: ").append(toIndentedString(dealNumber)).append("\n");
    sb.append("    dealType: ").append(toIndentedString(dealType)).append("\n");
    sb.append("    dealSubType: ").append(toIndentedString(dealSubType)).append("\n");
    sb.append("    sapDealType: ").append(toIndentedString(sapDealType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

