/*
 * Customer Update Integration API
 * OICC API will process OICC request and broadcast to downstream applications via broadcast API.  Briefly, OICC will call customer API to match/create/update customer profile for all involve parties,  then call SAP if required, after SAP process success broad cast CustomerProfileChangeEvent or  OwnershipChangeEvent accordingly.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.Incentive;
import ca.toyota.bizservice.api.cdms.OiccExtraInfoDeal;
import ca.toyota.bizservice.api.cdms.OiccExtraInfoSales;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;

/**
 * OiccExtraInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:37.695-05:00")
public class OiccExtraInfo {
  @JsonProperty("dealerCode")
  private String dealerCode = null;

  @JsonProperty("tcciFinanceIndicator")
  private Boolean tcciFinanceIndicator = null;

  @JsonProperty("registrationDate")
  private LocalDate registrationDate = null;

  @JsonProperty("deliveryDate")
  private LocalDate deliveryDate = null;

  @JsonProperty("tcuvNumber")
  private String tcuvNumber = null;

  @JsonProperty("sales")
  private OiccExtraInfoSales sales = null;

  @JsonProperty("deal")
  private OiccExtraInfoDeal deal = null;

  @JsonProperty("oiccCampainNumber")
  private String oiccCampainNumber = null;

  @JsonProperty("incentive")
  private Incentive incentive = null;

  /**
   * ORP indicator, for RDR, ORP only applies to owner or leesee with sales type &#x3D; ‘1A’. ‘3F’. ‘3D’. For OICC dealer user have a choice to set ORP to true, false but this option is conditional available to user
   */
  public enum OrpIndicatorEnum {
    Y("Y"),
    
    N("N");

    private String value;

    OrpIndicatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OrpIndicatorEnum fromValue(String text) {
      for (OrpIndicatorEnum b : OrpIndicatorEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("orpIndicator")
  private OrpIndicatorEnum orpIndicator = null;

  public OiccExtraInfo dealerCode(String dealerCode) {
    this.dealerCode = dealerCode;
    return this;
  }

   /**
   * Get dealerCode
   * @return dealerCode
  **/
  @ApiModelProperty(value = "")
  public String getDealerCode() {
    return dealerCode;
  }

  public void setDealerCode(String dealerCode) {
    this.dealerCode = dealerCode;
  }

  public OiccExtraInfo tcciFinanceIndicator(Boolean tcciFinanceIndicator) {
    this.tcciFinanceIndicator = tcciFinanceIndicator;
    return this;
  }

   /**
   * Get tcciFinanceIndicator
   * @return tcciFinanceIndicator
  **/
  @ApiModelProperty(value = "")
  public Boolean isTcciFinanceIndicator() {
    return tcciFinanceIndicator;
  }

  public void setTcciFinanceIndicator(Boolean tcciFinanceIndicator) {
    this.tcciFinanceIndicator = tcciFinanceIndicator;
  }

  public OiccExtraInfo registrationDate(LocalDate registrationDate) {
    this.registrationDate = registrationDate;
    return this;
  }

   /**
   * Get registrationDate
   * @return registrationDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getRegistrationDate() {
    return registrationDate;
  }

  public void setRegistrationDate(LocalDate registrationDate) {
    this.registrationDate = registrationDate;
  }

  public OiccExtraInfo deliveryDate(LocalDate deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }

   /**
   * Get deliveryDate
   * @return deliveryDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(LocalDate deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  public OiccExtraInfo tcuvNumber(String tcuvNumber) {
    this.tcuvNumber = tcuvNumber;
    return this;
  }

   /**
   * Get tcuvNumber
   * @return tcuvNumber
  **/
  @ApiModelProperty(value = "")
  public String getTcuvNumber() {
    return tcuvNumber;
  }

  public void setTcuvNumber(String tcuvNumber) {
    this.tcuvNumber = tcuvNumber;
  }

  public OiccExtraInfo sales(OiccExtraInfoSales sales) {
    this.sales = sales;
    return this;
  }

   /**
   * Get sales
   * @return sales
  **/
  @ApiModelProperty(value = "")
  public OiccExtraInfoSales getSales() {
    return sales;
  }

  public void setSales(OiccExtraInfoSales sales) {
    this.sales = sales;
  }

  public OiccExtraInfo deal(OiccExtraInfoDeal deal) {
    this.deal = deal;
    return this;
  }

   /**
   * Get deal
   * @return deal
  **/
  @ApiModelProperty(value = "")
  public OiccExtraInfoDeal getDeal() {
    return deal;
  }

  public void setDeal(OiccExtraInfoDeal deal) {
    this.deal = deal;
  }

  public OiccExtraInfo oiccCampainNumber(String oiccCampainNumber) {
    this.oiccCampainNumber = oiccCampainNumber;
    return this;
  }

   /**
   * Get oiccCampainNumber
   * @return oiccCampainNumber
  **/
  @ApiModelProperty(example = "A1234", value = "")
  public String getOiccCampainNumber() {
    return oiccCampainNumber;
  }

  public void setOiccCampainNumber(String oiccCampainNumber) {
    this.oiccCampainNumber = oiccCampainNumber;
  }

  public OiccExtraInfo incentive(Incentive incentive) {
    this.incentive = incentive;
    return this;
  }

   /**
   * Get incentive
   * @return incentive
  **/
  @ApiModelProperty(value = "")
  public Incentive getIncentive() {
    return incentive;
  }

  public void setIncentive(Incentive incentive) {
    this.incentive = incentive;
  }

  public OiccExtraInfo orpIndicator(OrpIndicatorEnum orpIndicator) {
    this.orpIndicator = orpIndicator;
    return this;
  }

   /**
   * ORP indicator, for RDR, ORP only applies to owner or leesee with sales type &#x3D; ‘1A’. ‘3F’. ‘3D’. For OICC dealer user have a choice to set ORP to true, false but this option is conditional available to user
   * @return orpIndicator
  **/
  @ApiModelProperty(value = "ORP indicator, for RDR, ORP only applies to owner or leesee with sales type = ‘1A’. ‘3F’. ‘3D’. For OICC dealer user have a choice to set ORP to true, false but this option is conditional available to user")
  public OrpIndicatorEnum getOrpIndicator() {
    return orpIndicator;
  }

  public void setOrpIndicator(OrpIndicatorEnum orpIndicator) {
    this.orpIndicator = orpIndicator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OiccExtraInfo oiccExtraInfo = (OiccExtraInfo) o;
    return Objects.equals(this.dealerCode, oiccExtraInfo.dealerCode) &&
        Objects.equals(this.tcciFinanceIndicator, oiccExtraInfo.tcciFinanceIndicator) &&
        Objects.equals(this.registrationDate, oiccExtraInfo.registrationDate) &&
        Objects.equals(this.deliveryDate, oiccExtraInfo.deliveryDate) &&
        Objects.equals(this.tcuvNumber, oiccExtraInfo.tcuvNumber) &&
        Objects.equals(this.sales, oiccExtraInfo.sales) &&
        Objects.equals(this.deal, oiccExtraInfo.deal) &&
        Objects.equals(this.oiccCampainNumber, oiccExtraInfo.oiccCampainNumber) &&
        Objects.equals(this.incentive, oiccExtraInfo.incentive) &&
        Objects.equals(this.orpIndicator, oiccExtraInfo.orpIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dealerCode, tcciFinanceIndicator, registrationDate, deliveryDate, tcuvNumber, sales, deal, oiccCampainNumber, incentive, orpIndicator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OiccExtraInfo {\n");
    
    sb.append("    dealerCode: ").append(toIndentedString(dealerCode)).append("\n");
    sb.append("    tcciFinanceIndicator: ").append(toIndentedString(tcciFinanceIndicator)).append("\n");
    sb.append("    registrationDate: ").append(toIndentedString(registrationDate)).append("\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("    tcuvNumber: ").append(toIndentedString(tcuvNumber)).append("\n");
    sb.append("    sales: ").append(toIndentedString(sales)).append("\n");
    sb.append("    deal: ").append(toIndentedString(deal)).append("\n");
    sb.append("    oiccCampainNumber: ").append(toIndentedString(oiccCampainNumber)).append("\n");
    sb.append("    incentive: ").append(toIndentedString(incentive)).append("\n");
    sb.append("    orpIndicator: ").append(toIndentedString(orpIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

