/*
 * CDMS Customer API
 * CDMS Customer API will provide a set of the REST API for operations on Customer Data Management System (CDMS)
 *
 * OpenAPI spec version: 1.0
 * Contact: johnson_ouyang@toyota.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.RequestHeader;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;

/**
 * OwnershipDateRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:36.821-05:00")
public class OwnershipDateRequest {
  @JsonProperty("requestHeader")
  private RequestHeader requestHeader = null;

  @JsonProperty("ownershipStartDate")
  private LocalDate ownershipStartDate = null;

  @JsonProperty("originalOwnershipStartDate")
  private LocalDate originalOwnershipStartDate = null;

  public OwnershipDateRequest requestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
    return this;
  }

   /**
   * Get requestHeader
   * @return requestHeader
  **/
  @ApiModelProperty(required = true, value = "")
  public RequestHeader getRequestHeader() {
    return requestHeader;
  }

  public void setRequestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
  }

  public OwnershipDateRequest ownershipStartDate(LocalDate ownershipStartDate) {
    this.ownershipStartDate = ownershipStartDate;
    return this;
  }

   /**
   * Get ownershipStartDate
   * @return ownershipStartDate
  **/
  @ApiModelProperty(required = true, value = "")
  public LocalDate getOwnershipStartDate() {
    return ownershipStartDate;
  }

  public void setOwnershipStartDate(LocalDate ownershipStartDate) {
    this.ownershipStartDate = ownershipStartDate;
  }

  public OwnershipDateRequest originalOwnershipStartDate(LocalDate originalOwnershipStartDate) {
    this.originalOwnershipStartDate = originalOwnershipStartDate;
    return this;
  }

   /**
   * Get originalOwnershipStartDate
   * @return originalOwnershipStartDate
  **/
  @ApiModelProperty(required = true, value = "")
  public LocalDate getOriginalOwnershipStartDate() {
    return originalOwnershipStartDate;
  }

  public void setOriginalOwnershipStartDate(LocalDate originalOwnershipStartDate) {
    this.originalOwnershipStartDate = originalOwnershipStartDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OwnershipDateRequest ownershipDateRequest = (OwnershipDateRequest) o;
    return Objects.equals(this.requestHeader, ownershipDateRequest.requestHeader) &&
        Objects.equals(this.ownershipStartDate, ownershipDateRequest.ownershipStartDate) &&
        Objects.equals(this.originalOwnershipStartDate, ownershipDateRequest.originalOwnershipStartDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestHeader, ownershipStartDate, originalOwnershipStartDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OwnershipDateRequest {\n");
    
    sb.append("    requestHeader: ").append(toIndentedString(requestHeader)).append("\n");
    sb.append("    ownershipStartDate: ").append(toIndentedString(ownershipStartDate)).append("\n");
    sb.append("    originalOwnershipStartDate: ").append(toIndentedString(originalOwnershipStartDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

