/*
 * CDMS Customer API
 * CDMS Customer API will provide a set of the REST API for operations on Customer Data Management System (CDMS)
 *
 * OpenAPI spec version: 1.0
 * Contact: johnson_ouyang@toyota.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.ResponseHeader;
import ca.toyota.bizservice.api.cdms.VehicleOwnership;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Response for the vehicle ownership APIs
 */
@ApiModel(description = "Response for the vehicle ownership APIs")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:36.821-05:00")
public class OwnershipResponse {
  @JsonProperty("responseHeader")
  private ResponseHeader responseHeader = null;

  @JsonProperty("vehicleOwnership")
  private VehicleOwnership vehicleOwnership = null;

  public OwnershipResponse responseHeader(ResponseHeader responseHeader) {
    this.responseHeader = responseHeader;
    return this;
  }

   /**
   * Get responseHeader
   * @return responseHeader
  **/
  @ApiModelProperty(required = true, value = "")
  public ResponseHeader getResponseHeader() {
    return responseHeader;
  }

  public void setResponseHeader(ResponseHeader responseHeader) {
    this.responseHeader = responseHeader;
  }

  public OwnershipResponse vehicleOwnership(VehicleOwnership vehicleOwnership) {
    this.vehicleOwnership = vehicleOwnership;
    return this;
  }

   /**
   * Get vehicleOwnership
   * @return vehicleOwnership
  **/
  @ApiModelProperty(value = "")
  public VehicleOwnership getVehicleOwnership() {
    return vehicleOwnership;
  }

  public void setVehicleOwnership(VehicleOwnership vehicleOwnership) {
    this.vehicleOwnership = vehicleOwnership;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OwnershipResponse ownershipResponse = (OwnershipResponse) o;
    return Objects.equals(this.responseHeader, ownershipResponse.responseHeader) &&
        Objects.equals(this.vehicleOwnership, ownershipResponse.vehicleOwnership);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseHeader, vehicleOwnership);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OwnershipResponse {\n");
    
    sb.append("    responseHeader: ").append(toIndentedString(responseHeader)).append("\n");
    sb.append("    vehicleOwnership: ").append(toIndentedString(vehicleOwnership)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

