/*
 * Customer Update Integration API
 * OICC API will process OICC request and broadcast to downstream applications via broadcast API.  Briefly, OICC will call customer API to match/create/update customer profile for all involve parties,  then call SAP if required, after SAP process success broad cast CustomerProfileChangeEvent or  OwnershipChangeEvent accordingly.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.time.OffsetDateTime;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * A specific individual
 */
@ApiModel(description = "A specific individual")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:37.695-05:00")
public class Person {
  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("middleName")
  private String middleName = null;

  @JsonProperty("familyName")
  private String familyName = null;

  @JsonProperty("salutation")
  private String salutation = null;

  @JsonProperty("birthDate")
  private LocalDate birthDate = null;

  @JsonProperty("deceasedDate")
  @JsonFormat(pattern= "yyyy-MM-dd")
  private LocalDate deceasedDate = null;

  @JsonProperty("deceasedSourceCode")
  private String deceasedSourceCode = null;

  @JsonProperty("PrivacyConsentCode")
  private String privacyConsentCode = null;

  @JsonProperty("PrivacyConsentDate")
  @JsonFormat(pattern= "yyyy-MM-dd")
  private LocalDate privacyConsentDate = null;

  @JsonProperty("lastUpdateTimestamp")
  private OffsetDateTime lastUpdateTimestamp = null;

  @JsonProperty("lastUpdateUserID")
  private String lastUpdateUserID = null;

  @JsonProperty("LastUpdateSource")
  private String lastUpdateSource = null;

  public Person firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Given name
   * @return firstName
  **/
  @ApiModelProperty(required = true, value = "Given name")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Person middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Middle intial of the person
   * @return middleName
  **/
  @ApiModelProperty(value = "Middle intial of the person")
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public Person familyName(String familyName) {
    this.familyName = familyName;
    return this;
  }

   /**
   * Family name
   * @return familyName
  **/
  @ApiModelProperty(required = true, value = "Family name")
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }

  public Person salutation(String salutation) {
    this.salutation = salutation;
    return this;
  }

   /**
   * A word or phrase of greeting used to begin a letter or message.
   * @return salutation
  **/
  @ApiModelProperty(value = "A word or phrase of greeting used to begin a letter or message.")
  public String getSalutation() {
    return salutation;
  }

  public void setSalutation(String salutation) {
    this.salutation = salutation;
  }

  public Person birthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * Birth date of the person
   * @return birthDate
  **/
  @ApiModelProperty(value = "Birth date of the person")
  public LocalDate getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
  }

  public Person deceasedDate(LocalDate deceasedDate) {
    this.deceasedDate = deceasedDate;
    return this;
  }

   /**
   * Death date of the person
   * @return deceasedDate
  **/
  @ApiModelProperty(value = "Death date of the person")
  public LocalDate getDeceasedDate() {
    return deceasedDate;
  }

  public void setDeceasedDate(LocalDate deceasedDate) {
    this.deceasedDate = deceasedDate;
  }

  public Person deceasedSourceCode(String deceasedSourceCode) {
    this.deceasedSourceCode = deceasedSourceCode;
    return this;
  }

   /**
   * Source code identifying an application making the deceased date to be updated
   * @return deceasedSourceCode
  **/
  @ApiModelProperty(value = "Source code identifying an application making the deceased date to be updated")
  public String getDeceasedSourceCode() {
    return deceasedSourceCode;
  }

  public void setDeceasedSourceCode(String deceasedSourceCode) {
    this.deceasedSourceCode = deceasedSourceCode;
  }

  public Person privacyConsentCode(String privacyConsentCode) {
    this.privacyConsentCode = privacyConsentCode;
    return this;
  }

   /**
   * Source code identifying an application for the privacy consent (RDR, CIC, VIC, TCIMLR etc.)
   * @return privacyConsentCode
  **/
  @ApiModelProperty(value = "Source code identifying an application for the privacy consent (RDR, CIC, VIC, TCIMLR etc.)")
  public String getPrivacyConsentCode() {
    return privacyConsentCode;
  }

  public void setPrivacyConsentCode(String privacyConsentCode) {
    this.privacyConsentCode = privacyConsentCode;
  }

  public Person privacyConsentDate(LocalDate privacyConsentDate) {
    this.privacyConsentDate = privacyConsentDate;
    return this;
  }

   /**
   * Start date for the privacy consent being applied
   * @return privacyConsentDate
  **/
  @ApiModelProperty(value = "Start date for the privacy consent being applied")
  public LocalDate getPrivacyConsentDate() {
    return privacyConsentDate;
  }

  public void setPrivacyConsentDate(LocalDate privacyConsentDate) {
    this.privacyConsentDate = privacyConsentDate;
  }

  public Person lastUpdateTimestamp(OffsetDateTime lastUpdateTimestamp) {
    this.lastUpdateTimestamp = lastUpdateTimestamp;
    return this;
  }

   /**
   * Last date and time for updating the person
   * @return lastUpdateTimestamp
  **/
  @ApiModelProperty(value = "Last date and time for updating the person")
  public OffsetDateTime getLastUpdateTimestamp() {
    return lastUpdateTimestamp;
  }

  public void setLastUpdateTimestamp(OffsetDateTime lastUpdateTimestamp) {
    this.lastUpdateTimestamp = lastUpdateTimestamp;
  }

  public Person lastUpdateUserID(String lastUpdateUserID) {
    this.lastUpdateUserID = lastUpdateUserID;
    return this;
  }

   /**
   * Last userID updating the person
   * @return lastUpdateUserID
  **/
  @ApiModelProperty(value = "Last userID updating the person")
  public String getLastUpdateUserID() {
    return lastUpdateUserID;
  }

  public void setLastUpdateUserID(String lastUpdateUserID) {
    this.lastUpdateUserID = lastUpdateUserID;
  }

  public Person lastUpdateSource(String lastUpdateSource) {
    this.lastUpdateSource = lastUpdateSource;
    return this;
  }

   /**
   * Last application updating the person
   * @return lastUpdateSource
  **/
  @ApiModelProperty(value = "Last application updating the person")
  public String getLastUpdateSource() {
    return lastUpdateSource;
  }

  public void setLastUpdateSource(String lastUpdateSource) {
    this.lastUpdateSource = lastUpdateSource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Person person = (Person) o;
    return Objects.equals(this.firstName, person.firstName) &&
        Objects.equals(this.middleName, person.middleName) &&
        Objects.equals(this.familyName, person.familyName) &&
        Objects.equals(this.salutation, person.salutation) &&
        Objects.equals(this.birthDate, person.birthDate) &&
        Objects.equals(this.deceasedDate, person.deceasedDate) &&
        Objects.equals(this.deceasedSourceCode, person.deceasedSourceCode) &&
        Objects.equals(this.privacyConsentCode, person.privacyConsentCode) &&
        Objects.equals(this.privacyConsentDate, person.privacyConsentDate) &&
        Objects.equals(this.lastUpdateTimestamp, person.lastUpdateTimestamp) &&
        Objects.equals(this.lastUpdateUserID, person.lastUpdateUserID) &&
        Objects.equals(this.lastUpdateSource, person.lastUpdateSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, middleName, familyName, salutation, birthDate, deceasedDate, deceasedSourceCode, privacyConsentCode, privacyConsentDate, lastUpdateTimestamp, lastUpdateUserID, lastUpdateSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Person {\n");
    
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    salutation: ").append(toIndentedString(salutation)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    deceasedDate: ").append(toIndentedString(deceasedDate)).append("\n");
    sb.append("    deceasedSourceCode: ").append(toIndentedString(deceasedSourceCode)).append("\n");
    sb.append("    privacyConsentCode: ").append(toIndentedString(privacyConsentCode)).append("\n");
    sb.append("    privacyConsentDate: ").append(toIndentedString(privacyConsentDate)).append("\n");
    sb.append("    lastUpdateTimestamp: ").append(toIndentedString(lastUpdateTimestamp)).append("\n");
    sb.append("    lastUpdateUserID: ").append(toIndentedString(lastUpdateUserID)).append("\n");
    sb.append("    lastUpdateSource: ").append(toIndentedString(lastUpdateSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

