/*
 * CDMS Customer API
 * CDMS Customer API will provide a set of the REST API for operations on Customer Data Management System (CDMS)
 *
 * OpenAPI spec version: 1.0
 * Contact: johnson_ouyang@toyota.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.RequestHeader;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;

/**
 * TerminateOwnershipRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:36.821-05:00")
public class TerminateOwnershipRequest {
  @JsonProperty("requestHeader")
  private RequestHeader requestHeader = null;

  @JsonProperty("ownershipStartDate")
  private LocalDate ownershipStartDate = null;

  @JsonProperty("ownershipEndDate")
  private LocalDate ownershipEndDate = null;

  /**
   * Vehicle ownership end reason code
   */
  public enum OwnershipEndReasonEnum {
    A("A"),
    
    I("I"),
    
    O("O"),
    
    S("S"),
    
    T("T"),
    
    W("W");

    private String value;

    OwnershipEndReasonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OwnershipEndReasonEnum fromValue(String text) {
      for (OwnershipEndReasonEnum b : OwnershipEndReasonEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("ownershipEndReason")
  private OwnershipEndReasonEnum ownershipEndReason = null;

  public TerminateOwnershipRequest requestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
    return this;
  }

   /**
   * Get requestHeader
   * @return requestHeader
  **/
  @ApiModelProperty(required = true, value = "")
  public RequestHeader getRequestHeader() {
    return requestHeader;
  }

  public void setRequestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
  }

  public TerminateOwnershipRequest ownershipStartDate(LocalDate ownershipStartDate) {
    this.ownershipStartDate = ownershipStartDate;
    return this;
  }

   /**
   * Ownership start date
   * @return ownershipStartDate
  **/
  @ApiModelProperty(value = "Ownership start date")
  public LocalDate getOwnershipStartDate() {
    return ownershipStartDate;
  }

  public void setOwnershipStartDate(LocalDate ownershipStartDate) {
    this.ownershipStartDate = ownershipStartDate;
  }

  public TerminateOwnershipRequest ownershipEndDate(LocalDate ownershipEndDate) {
    this.ownershipEndDate = ownershipEndDate;
    return this;
  }

   /**
   * Start date when the specified VIN was disassociated with the customer
   * @return ownershipEndDate
  **/
  @ApiModelProperty(required = true, value = "Start date when the specified VIN was disassociated with the customer")
  public LocalDate getOwnershipEndDate() {
    return ownershipEndDate;
  }

  public void setOwnershipEndDate(LocalDate ownershipEndDate) {
    this.ownershipEndDate = ownershipEndDate;
  }

  public TerminateOwnershipRequest ownershipEndReason(OwnershipEndReasonEnum ownershipEndReason) {
    this.ownershipEndReason = ownershipEndReason;
    return this;
  }

   /**
   * Vehicle ownership end reason code
   * @return ownershipEndReason
  **/
  @ApiModelProperty(required = true, value = "Vehicle ownership end reason code")
  public OwnershipEndReasonEnum getOwnershipEndReason() {
    return ownershipEndReason;
  }

  public void setOwnershipEndReason(OwnershipEndReasonEnum ownershipEndReason) {
    this.ownershipEndReason = ownershipEndReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerminateOwnershipRequest terminateOwnershipRequest = (TerminateOwnershipRequest) o;
    return Objects.equals(this.requestHeader, terminateOwnershipRequest.requestHeader) &&
        Objects.equals(this.ownershipStartDate, terminateOwnershipRequest.ownershipStartDate) &&
        Objects.equals(this.ownershipEndDate, terminateOwnershipRequest.ownershipEndDate) &&
        Objects.equals(this.ownershipEndReason, terminateOwnershipRequest.ownershipEndReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestHeader, ownershipStartDate, ownershipEndDate, ownershipEndReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerminateOwnershipRequest {\n");
    
    sb.append("    requestHeader: ").append(toIndentedString(requestHeader)).append("\n");
    sb.append("    ownershipStartDate: ").append(toIndentedString(ownershipStartDate)).append("\n");
    sb.append("    ownershipEndDate: ").append(toIndentedString(ownershipEndDate)).append("\n");
    sb.append("    ownershipEndReason: ").append(toIndentedString(ownershipEndReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

