/*
 * Customer Update Integration API
 * OICC API will process OICC request and broadcast to downstream applications via broadcast API.  Briefly, OICC will call customer API to match/create/update customer profile for all involve parties,  then call SAP if required, after SAP process success broad cast CustomerProfileChangeEvent or  OwnershipChangeEvent accordingly.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import ca.toyota.bizservice.api.cdms.Vehicle;
import ca.toyota.bizservice.api.cdms.VehicleOwnershipDetail;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * VehicleOwnership
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:37.695-05:00")
public class VehicleOwnership {
  /**
   * Sale type for a vehicle. 1A &#x3D; Retail, 1B &#x3D; Employee Purchase, 2C &#x3D; Demo, 3D &#x3D; Dealer Own Lease, 3E &#x3D; Independent Lease, 3F &#x3D; TCCI Lease, 4E &#x3D; Fleet Lease, 4G &#x3D; Fleet, 4J &#x3D; Daily Rental
   */
  public enum SaleTypeEnum {
    _1A("1A"),
    
    _1B("1B"),
    
    _2C("2C"),
    
    _3D("3D"),
    
    _3E("3E"),
    
    _3F("3F"),
    
    _4E("4E"),
    
    _4G("4G"),
    
    _4J("4J");

    private String value;

    SaleTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SaleTypeEnum fromValue(String text) {
      for (SaleTypeEnum b : SaleTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("saleType")
  private SaleTypeEnum saleType = null;

  @JsonProperty("vehicle")
  private Vehicle vehicle = null;

  @JsonProperty("vehicleOwnershipDetails")
  private List<VehicleOwnershipDetail> vehicleOwnershipDetails = new ArrayList<>();

  public VehicleOwnership saleType(SaleTypeEnum saleType) {
    this.saleType = saleType;
    return this;
  }

   /**
   * Sale type for a vehicle. 1A &#x3D; Retail, 1B &#x3D; Employee Purchase, 2C &#x3D; Demo, 3D &#x3D; Dealer Own Lease, 3E &#x3D; Independent Lease, 3F &#x3D; TCCI Lease, 4E &#x3D; Fleet Lease, 4G &#x3D; Fleet, 4J &#x3D; Daily Rental
   * @return saleType
  **/
  @ApiModelProperty(required = true, value = "Sale type for a vehicle. 1A = Retail, 1B = Employee Purchase, 2C = Demo, 3D = Dealer Own Lease, 3E = Independent Lease, 3F = TCCI Lease, 4E = Fleet Lease, 4G = Fleet, 4J = Daily Rental")
  public SaleTypeEnum getSaleType() {
    return saleType;
  }

  public void setSaleType(SaleTypeEnum saleType) {
    this.saleType = saleType;
  }

  public VehicleOwnership vehicle(Vehicle vehicle) {
    this.vehicle = vehicle;
    return this;
  }

   /**
   * Get vehicle
   * @return vehicle
  **/
  @ApiModelProperty(required = true, value = "")
  public Vehicle getVehicle() {
    return vehicle;
  }

  public void setVehicle(Vehicle vehicle) {
    this.vehicle = vehicle;
  }

  public VehicleOwnership vehicleOwnershipDetails(List<VehicleOwnershipDetail> vehicleOwnershipDetails) {
    this.vehicleOwnershipDetails = vehicleOwnershipDetails;
    return this;
  }

  public VehicleOwnership addVehicleOwnershipDetailsItem(VehicleOwnershipDetail vehicleOwnershipDetailsItem) {
    this.vehicleOwnershipDetails.add(vehicleOwnershipDetailsItem);
    return this;
  }

   /**
   * Get vehicleOwnershipDetails
   * @return vehicleOwnershipDetails
  **/
  @ApiModelProperty(required = true, value = "")
  public List<VehicleOwnershipDetail> getVehicleOwnershipDetails() {
    return vehicleOwnershipDetails;
  }

  public void setVehicleOwnershipDetails(List<VehicleOwnershipDetail> vehicleOwnershipDetails) {
    this.vehicleOwnershipDetails = vehicleOwnershipDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleOwnership vehicleOwnership = (VehicleOwnership) o;
    return Objects.equals(this.saleType, vehicleOwnership.saleType) &&
        Objects.equals(this.vehicle, vehicleOwnership.vehicle) &&
        Objects.equals(this.vehicleOwnershipDetails, vehicleOwnership.vehicleOwnershipDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saleType, vehicle, vehicleOwnershipDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleOwnership {\n");
    
    sb.append("    saleType: ").append(toIndentedString(saleType)).append("\n");
    sb.append("    vehicle: ").append(toIndentedString(vehicle)).append("\n");
    sb.append("    vehicleOwnershipDetails: ").append(toIndentedString(vehicleOwnershipDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

