/*
 * Customer Update Integration API
 * OICC API will process OICC request and broadcast to downstream applications via broadcast API.  Briefly, OICC will call customer API to match/create/update customer profile for all involve parties,  then call SAP if required, after SAP process success broad cast CustomerProfileChangeEvent or  OwnershipChangeEvent accordingly.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.toyota.bizservice.api.cdms;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;

/**
 * Vehicle
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-15T15:26:37.695-05:00")
public class Vehicle {
  @JsonProperty("vehicleID")
  private String vehicleID = null;

  /**
   * Vehicle make code
   */
  public enum VehicleMakeEnum {
    TOY("TOY");

    private String value;

    VehicleMakeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VehicleMakeEnum fromValue(String text) {
      for (VehicleMakeEnum b : VehicleMakeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("vehicleMake")
  private VehicleMakeEnum vehicleMake = null;

  /**
   * Brand code of a vehicle
   */
  public enum BrandEnum {
    TOY("TOY"),
    
    LEX("LEX");

    private String value;

    BrandEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BrandEnum fromValue(String text) {
      for (BrandEnum b : BrandEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("brand")
  private BrandEnum brand = null;

  @JsonProperty("model")
  private String model = null;

  @JsonProperty("modelYear")
  private String modelYear = null;

  @JsonProperty("modelDescription")
  private String modelDescription = null;

  @JsonProperty("seriesCode")
  private String seriesCode = null;

  @JsonProperty("seriesName")
  private String seriesName = null;

  @JsonProperty("registrationDate")
  private LocalDate registrationDate = null;

  @JsonProperty("vinInfoChangeSource")
  private String vinInfoChangeSource = null;

  @JsonProperty("vinOwnershipLastChangeDate")
  private LocalDate vinOwnershipLastChangeDate = null;

  @JsonProperty("originalRetailDealerCode")
  private String originalRetailDealerCode = null;

  public Vehicle vehicleID(String vehicleID) {
    this.vehicleID = vehicleID;
    return this;
  }

   /**
   * VIN
   * @return vehicleID
  **/
  @ApiModelProperty(example = "JTHHY5AY5JA000146", required = true, value = "VIN")
  public String getVehicleID() {
    return vehicleID;
  }

  public void setVehicleID(String vehicleID) {
    this.vehicleID = vehicleID;
  }

  public Vehicle vehicleMake(VehicleMakeEnum vehicleMake) {
    this.vehicleMake = vehicleMake;
    return this;
  }

   /**
   * Vehicle make code
   * @return vehicleMake
  **/
  @ApiModelProperty(value = "Vehicle make code")
  public VehicleMakeEnum getVehicleMake() {
    return vehicleMake;
  }

  public void setVehicleMake(VehicleMakeEnum vehicleMake) {
    this.vehicleMake = vehicleMake;
  }

  public Vehicle brand(BrandEnum brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Brand code of a vehicle
   * @return brand
  **/
  @ApiModelProperty(example = "TOY", value = "Brand code of a vehicle")
  public BrandEnum getBrand() {
    return brand;
  }

  public void setBrand(BrandEnum brand) {
    this.brand = brand;
  }

  public Vehicle model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Manufacturer-assigned model code of vehicle
   * @return model
  **/
  @ApiModelProperty(example = "KY5F1T", value = "Manufacturer-assigned model code of vehicle")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public Vehicle modelYear(String modelYear) {
    this.modelYear = modelYear;
    return this;
  }

   /**
   * Get modelYear
   * @return modelYear
  **/
  @ApiModelProperty(example = "2018", value = "")
  public String getModelYear() {
    return modelYear;
  }

  public void setModelYear(String modelYear) {
    this.modelYear = modelYear;
  }

  public Vehicle modelDescription(String modelDescription) {
    this.modelDescription = modelDescription;
    return this;
  }

   /**
   * Descriptive vehicle model name
   * @return modelDescription
  **/
  @ApiModelProperty(example = "4X4 TUNDRA REG CAB", value = "Descriptive vehicle model name")
  public String getModelDescription() {
    return modelDescription;
  }

  public void setModelDescription(String modelDescription) {
    this.modelDescription = modelDescription;
  }

  public Vehicle seriesCode(String seriesCode) {
    this.seriesCode = seriesCode;
    return this;
  }

   /**
   * The series code for the specified vehicle
   * @return seriesCode
  **/
  @ApiModelProperty(example = "TP4", value = "The series code for the specified vehicle")
  public String getSeriesCode() {
    return seriesCode;
  }

  public void setSeriesCode(String seriesCode) {
    this.seriesCode = seriesCode;
  }

  public Vehicle seriesName(String seriesName) {
    this.seriesName = seriesName;
    return this;
  }

   /**
   * The name corresponding to the SeriesCode
   * @return seriesName
  **/
  @ApiModelProperty(example = "TUNDRA 4X4", value = "The name corresponding to the SeriesCode")
  public String getSeriesName() {
    return seriesName;
  }

  public void setSeriesName(String seriesName) {
    this.seriesName = seriesName;
  }

  public Vehicle registrationDate(LocalDate registrationDate) {
    this.registrationDate = registrationDate;
    return this;
  }

   /**
   * Registration date for a vehicle
   * @return registrationDate
  **/
  @ApiModelProperty(value = "Registration date for a vehicle")
  public LocalDate getRegistrationDate() {
    return registrationDate;
  }

  public void setRegistrationDate(LocalDate registrationDate) {
    this.registrationDate = registrationDate;
  }

  public Vehicle vinInfoChangeSource(String vinInfoChangeSource) {
    this.vinInfoChangeSource = vinInfoChangeSource;
    return this;
  }

   /**
   * Get vinInfoChangeSource
   * @return vinInfoChangeSource
  **/
  @ApiModelProperty(value = "")
  public String getVinInfoChangeSource() {
    return vinInfoChangeSource;
  }

  public void setVinInfoChangeSource(String vinInfoChangeSource) {
    this.vinInfoChangeSource = vinInfoChangeSource;
  }

  public Vehicle vinOwnershipLastChangeDate(LocalDate vinOwnershipLastChangeDate) {
    this.vinOwnershipLastChangeDate = vinOwnershipLastChangeDate;
    return this;
  }

   /**
   * Get vinOwnershipLastChangeDate
   * @return vinOwnershipLastChangeDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getVinOwnershipLastChangeDate() {
    return vinOwnershipLastChangeDate;
  }

  public void setVinOwnershipLastChangeDate(LocalDate vinOwnershipLastChangeDate) {
    this.vinOwnershipLastChangeDate = vinOwnershipLastChangeDate;
  }

  public Vehicle originalRetailDealerCode(String originalRetailDealerCode) {
    this.originalRetailDealerCode = originalRetailDealerCode;
    return this;
  }

   /**
   * Get originalRetailDealerCode
   * @return originalRetailDealerCode
  **/
  @ApiModelProperty(value = "")
  public String getOriginalRetailDealerCode() {
    return originalRetailDealerCode;
  }

  public void setOriginalRetailDealerCode(String originalRetailDealerCode) {
    this.originalRetailDealerCode = originalRetailDealerCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vehicle vehicle = (Vehicle) o;
    return Objects.equals(this.vehicleID, vehicle.vehicleID) &&
        Objects.equals(this.vehicleMake, vehicle.vehicleMake) &&
        Objects.equals(this.brand, vehicle.brand) &&
        Objects.equals(this.model, vehicle.model) &&
        Objects.equals(this.modelYear, vehicle.modelYear) &&
        Objects.equals(this.modelDescription, vehicle.modelDescription) &&
        Objects.equals(this.seriesCode, vehicle.seriesCode) &&
        Objects.equals(this.seriesName, vehicle.seriesName) &&
        Objects.equals(this.registrationDate, vehicle.registrationDate) &&
        Objects.equals(this.vinInfoChangeSource, vehicle.vinInfoChangeSource) &&
        Objects.equals(this.vinOwnershipLastChangeDate, vehicle.vinOwnershipLastChangeDate) &&
        Objects.equals(this.originalRetailDealerCode, vehicle.originalRetailDealerCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vehicleID, vehicleMake, brand, model, modelYear, modelDescription, seriesCode, seriesName, registrationDate, vinInfoChangeSource, vinOwnershipLastChangeDate, originalRetailDealerCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vehicle {\n");
    
    sb.append("    vehicleID: ").append(toIndentedString(vehicleID)).append("\n");
    sb.append("    vehicleMake: ").append(toIndentedString(vehicleMake)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    modelYear: ").append(toIndentedString(modelYear)).append("\n");
    sb.append("    modelDescription: ").append(toIndentedString(modelDescription)).append("\n");
    sb.append("    seriesCode: ").append(toIndentedString(seriesCode)).append("\n");
    sb.append("    seriesName: ").append(toIndentedString(seriesName)).append("\n");
    sb.append("    registrationDate: ").append(toIndentedString(registrationDate)).append("\n");
    sb.append("    vinInfoChangeSource: ").append(toIndentedString(vinInfoChangeSource)).append("\n");
    sb.append("    vinOwnershipLastChangeDate: ").append(toIndentedString(vinOwnershipLastChangeDate)).append("\n");
    sb.append("    originalRetailDealerCode: ").append(toIndentedString(originalRetailDealerCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

